classDiagram
  class InputStream {
    <<interface>>
    +Read(char* buffer, std::streamsize size) std::streamsize = 0
    +Eof() bool = 0
  }

  class FileInputStream {
    -std::unique_ptr~std::ifstream~ m_file
    -std::string m_filename

    +FileInputStream(std::unique_ptr~std::ifstream~ file)
    +Read(char* buffer, std::streamsize size) std::streamsize
    +Eof() bool
  }

  class MemoryInputStream {
    -char* m_data
    -std::streamsize m_size
    -std::streamsize m_position

    +MemoryInputStream(const char* data, std::streamsize size)
    +Read(char* buffer, std::streamsize size) std::streamsize
    +Eof() bool
  }

  class OutputStream {
    <<interface>>
    +Write(const char* buffer, std::streamsize size) void = 0
    +Flush() void = 0
  }

  class FileOutputStream {
    -std::unique_ptr~std::ofstream~ m_file
    -std::string m_filename
    +FileOutputStream(std::unique_ptr~std::ofstream~ file)

    +Write(const char* buffer, std::streamsize size) void
    +Flush() void
  }

  class MemoryOutputStream {
    -std::vector<char> m_buffer

    +MemoryOutputStream()
    +Write(const char* buffer, std::streamsize size) void
    +Flush() void
    +Data() char*
    +Size() std::streamsize
  }

  InputStream <|.. FileInputStream
  InputStream <|.. MemoryInputStream
  OutputStream <|.. FileOutputStream
  OutputStream <|.. MemoryOutputStream
