classDiagram
    direction TB

    class IDrawable {
        + Draw(canvas: ICanvas&) void
    }

    class IStyle {
        + IsEnabled() optional~bool~
        + Enable(enable: bool) void
        + GetColor() optional~RGBAColor~
        + SetColor(color: RGBAColor) void
    }

    class IShape {
        + GetFrame() RectD
        + SetFrame(rect: RectD) void
        + GetOutlineStyle() IStyle&
        + GetFillStyle() IStyle&
        + GetGroup() std:: shared_ptr~IGroupShape~
        + GetGroup() std:: shared_ptr~IGroupShape~
    }

    class IShapes {
        + GetShapesCount() size_t
        + InsertShape(shape: std:: shared_ptr~IShape~, position: size_t) void
        + GetShapeAtIndex(index: size_t) std:: shared_ptr~IShape~
        + RemoveShapeAtIndex(index: size_t) void
    }

    class IGroupShape {
    }

    class SimpleShape {
        + SimpleShape(drawingStrategy: DrawingStrategy)
    }

    class GroupShape {
    }

    class ISlide {
        + GetWidth() double
        + GetHeight() double
        + GetShapes() IShapes&
    }

    class Slide {
    }

    namespace gfx {
        class ICanvas {
            + SetLineColor(color RGBAColor) void
            + BeginFill(color RGBAColor) void
            + EndFill() void
            + MoveTo(x: double, y: double) void
            + LineTo(x: double, y: double) void
            + DrawEllipse(left: double, top: double, width: double, height: double) void
        }

        class SFMLCanvas {
        }
    }

%% Drawable
    IDrawable <|.. IShape
    IDrawable <|.. ISlide
    IShape <|.. SimpleShape
    IShape <|.. GroupShape
    IShapes <|.. IGroupShape
    IGroupShape <|.. GroupShape
    ISlide <|.. Slide
%% Canvas
    ICanvas <|.. SFMLCanvas



