classDiagram
    direction TB


    class client {
    }

    namespace factory {
        class ICommandFactory {
            + CreateCommand() ICommand
            + CanCreateCommand() bool
            + AppendCommand(name: string, command: ICommand)
        }

        class AbstractCommandFactory {
            + AbstractCommandFactory(document: IDocument&)

            # m_document: std::shared_ptr~IDocument~
        }

        class DocumentCommandFactory {
            + DocumentCommandFactory(stream: std::istream&)

            - CreateInsertParagraph(std::string arguments) void
            - CreateInsertImage(std::string arguments) void
            - CreateSetTitle(std::string arguments) void
            - CreateList() void
            - CreateReplaceText(std::string arguments) void
            - CreateResizeImage(std::string arguments) void
            - CreateDeleteItem(std::string arguments) void
            - CreateHelp() void
            - CreateUndo() void
            - CreateRedo() void
            - CreateSave(std::string arguments) void

            - m_stream: std::unique_ptr~std::istream~
            - m_macroCommands: std::map~std::string, std::vector~ICommand~~
        }
    }

    namespace command {
        class ICommand:::tested {
            + Execute() void
        }

        class AbstractCommand:::tested {
            # m_document: IDocument&
        }

        class UnexecutableCommand {
            + Unexecute() void
            + IsExecuted() bool
            # m_executed: bool
        }

        class MergableCommand {
            + TryReplace(command: MergableCommand&) void
        }

        class StartMacroRecordingCommand {
            + StartMacroRecordingCommand(factory: ICommandFactory)
        }

        class EndMacroRecordingCommand {
            + EndMacroRecordingCommand(factory: ICommandFactory)
        }

        class MacroExecutionCommand {
            + MacroExecutionCommand(document: IDocument)
        }

        class InsertParagraphCommand {
            + InsertParagraphCommand(document: IDocument, position: std::optional~size_t~, text: std::string)
        }

        class InsertImageCommand {
            + InsertImageCommand(document: IDocument, position: std::optional~size_t~, width: int, height: int)
        }

        class SetTitleCommand {
            + SetTitleCommand(document: IDocument, newTitle: std::string)
        }

        class ListCommand:::tested {
            + ListCommand(document: IDocument)
        }

        class ReplaceTextCommand {
            + ReplaceTextCommand(document: IDocument, position: size_t, newText: string)
        }

        class ResizeImageCommand {
            + ResizeImageCommand(document: IDocument, position: size_t, newWidth: int, newHeight: int)
        }

        class DeleteItemCommand {
            + DeleteItemCommand(document: IDocument, position: size_t)
        }

        class HelpCommand:::tested {
            + HelpCommand()
        }

        class UndoCommand:::tested {
            + UndoCommand(document: IDocument)
        }

        class RedoCommand:::tested {
            + RedoCommand(document: IDocument)
        }

        class SaveCommand:::tested {
            + SaveCommand(document: IDocument, path: string)
        }
    }

    namespace invoker {

        class ICommandManager {
            + ExecuteAndAddCommand(command: ICommand&&)
        }

        class ConsoleCommandExecutor {
            + ConsoleCommandExecutor(commandManager: ICommandManager&, factory: ICommandFactory&)
            + Start() void

            - factory: std::unique_ptr~ICommandFactory~
            - manager: std::shared_ptr~ICommandManager~
        }

    }

    namespace history {

        class IHistoryManager {
            + Undo() void
            + Redo() void
            + CanUndo() bool
            + CanRedo() bool
        }

        class CommandHistoryManager {
            - m_commands: std::list~ICommand~
            - m_currentActionIndex: std::list~ICommand~::iterator
        }

    }

    namespace resiever {

        class IDocument:::tested {
            + InsertParagraph(text: string, position: optional~size_t~ = none) shared_ptr~IParagraph~
            + InsertImage(path: Path, width: int, height: int, position: optional~size_t~ = none) shared_ptr~IImage~
            + GetItemsCount() size_t
            + GetItem(index: size_t) ConstDocumentItem
            + GetItem(index: size_t) DocumentItem
            + DeleteItem(index: size_t) void
            + GetTitle() string
            + SetTitle(title: string) void
            + CanUndo() bool
            + Undo() void
            + CanRedo() bool
            + Redo() void
            + Save(path: Path) void
        }

        class HtmlDocument:::tested {
            - m_items: std::vector~DocumentItem~
        }

        class IParagraph:::tested {
            + GetText() const string
            + SetText(text: const string&) void
        }

        class IImage:::tested {
            + GetPath() const Path
            + GetWidth() const int

            + GetHeight() const int

            + Resize(int width, int height) void
        }

        class Paragraph:::tested {
        }

        class Image:::tested {
        }

        class ConstDocumentItem:::tested {
            + ConstDocumentItem(paragraph: std::shared_ptr~IParagraph~, isDeleted: bool = false)
            + ConstDocumentItem(image: std::shared_ptr~IImage~, isDeleted: bool = false)
            + GetImage() const shared_ptr~IImage~
            + GetParagraph() const shared_ptr~IParagraph~
            + IsDeleted() bool

            -m_isDeleted: const bool = false
        }

        class DocumentItem:::tested {
            + DocumentItem(paragraph: std::shared_ptr~IParagraph~, isDeleted: bool = false)
            + DocumentItem(image: std::shared_ptr~IImage~, isDeleted: bool = false)

            + GetImage() shared_ptr~IImage~
            + GetParagraph() shared_ptr~IParagraph~
            + IsDeleted() bool
            + SetIsDeleted(isDeleted: bool) void

            -m_isDeleted: bool = false
        }
    }

    %% Client
    client ..> CommandHistoryManager : creates
    client ..> ICommandFactory : creates
    client ..> HtmlDocument : creates

    client *--> ConsoleCommandExecutor

    %% Factory
    ICommandFactory <|.. AbstractCommandFactory
    AbstractCommandFactory <|-- DocumentCommandFactory
    AbstractCommandFactory o--> IDocument
    ICommandFactory ..> ICommand : creates

    %% Invoker
    ConsoleCommandExecutor o--> ICommandManager
    ConsoleCommandExecutor *--> ICommandFactory


    %% History
    IHistoryManager <|.. CommandHistoryManager
    ICommandManager <|.. CommandHistoryManager

    CommandHistoryManager *--> ICommand

    %% Document
    IDocument <|.. HtmlDocument
    HtmlDocument *--> DocumentItem
    DocumentItem o--> IParagraph
    DocumentItem o--> IImage
    IParagraph <|.. Paragraph
    IImage <|.. Image
    DocumentItem ..> ConstDocumentItem

    HtmlDocument o--> IHistoryManager

    %% Commands
    ICommand <|.. AbstractCommand
    ICommand <|.. HelpCommand
    AbstractCommand <|-- UnexecutableCommand

    AbstractCommand o--> IDocument

    AbstractCommand <|-- ListCommand
    AbstractCommand <|-- RedoCommand
    AbstractCommand <|-- UndoCommand
    AbstractCommand <|-- SaveCommand
    AbstractCommand <|-- StartMacroRecordingCommand
    AbstractCommand <|-- EndMacroRecordingCommand

    UnexecutableCommand <|-- InsertParagraphCommand
    UnexecutableCommand <|-- InsertImageCommand
    UnexecutableCommand <|-- SetTitleCommand
    UnexecutableCommand <|-- DeleteItemCommand
    UnexecutableCommand <|-- ResizeImageCommand
    UnexecutableCommand <|-- MacroExecutionCommand

    UnexecutableCommand <|-- MergableCommand
    MergableCommand <|-- ReplaceTextCommand

    classDef tested fill:#CCEEFF,stroke:#333,stroke-width:2px;
    classDef created fill:#FBE6FF,stroke:#333,stroke-width:2px;
