classDiagram

    namespace performer {
        class IDesigner {
            <<interface>>
            + CreateDraft(strm):PictureDraft
        }

        class Designer {
            + CreateDraft(strm)
        }

        class Client

        class Painter {
            + DrawPicture(draft, canvas)
        }
    }

    namespace shapes {

        class PictureDraft {
            + GetShapeCount()
            + GetShape(index):Shape
        }

        class Shape {
            + Draw(canvas:ICanvas)
            + GetColor()
        }

        class Rectangle {
            + Draw(canvas)
            + GetLeftTop()
            + GetRightBottom()
        }

        class Triangle {
            + Draw(canvas)
            + GetVertex(1)
            + GetVertex(2)
            + GetVertex(3)
        }

        class Ellipse {
            + Draw(canvas)
            + GetCenter()
            + GetHorizontalRadius()
            + GetVerticalRadius()
        }

        class RegularPolygon {
            + Draw(canvas)
            + GetVertexCount()
            + GetCenter()
            + GetRadius()
        }
    }



    namespace gfx {
        class Color {
            <<enumeration>>
            + Green
            + Red
            + Blue
            + Yellow
            + Pink
            + Black
        }

        class Canvas {
            + SetColor(color)
            + DrawLine(from, to)
            + DrawEllipse(l, t, w, h)
        }

        class ICanvas {
            <<interface>>
            + SetColor(color)
            + DrawLine(from, to)
            + DrawEllipse(l, t, w, h)
        }
    }



    namespace factory {
        class IShapeFactory {
            <<interface>>
            + CreateShape(descr:string):Shape
        }

        class ShapeFactory {
            + createShape(descr):Shape
        }
    }


    Shape <|-- Rectangle 
    Shape <|-- Triangle
    Shape <|-- Ellipse
    Shape <|-- RegularPolygon
    PictureDraft "1" *-- "0..*" Shape
    Designer ..> PictureDraft
    Painter ..> PictureDraft

    ICanvas <|.. Canvas

    Painter ..> ICanvas
    Shape ..> ICanvas

    Client *--> ICanvas
    ICanvas ..> Color

    IShapeFactory <|.. ShapeFactory 
    IShapeFactory ..> Shape
    Designer *--> IShapeFactory

    IDesigner <|.. Designer
    Client ..> IDesigner
    Client ..> Painter

