classDiagram
  direction TB

  class SubscribeType {
    <<enum>>
    +TEMPERAURE_CHANGE
    +HUMIDITY_CHANGE
    +PRESSURE_CHANGE
  }

  class IObserver {
    <<interface>>
    +Update() void
  }

  class AbstractObserver {
    +AbstractObserver(ISubject* subject)
    +GetSubject() std::weak_ptr~ISubject~
    -std::weak_ptr~ISubject~ m_subject
  }

  class AbstractStatsObserver {
    #UpdateStatistics(value) void
    #PrintValues(name) void
    -ValueType m_minValue
    -ValueType m_maxValue
    -ValueType m_accValue
  }

  class Display {
    -Update() void
  }

  class PressureStatsDisplay {
    -Update() void
  }
  class HumStatsDisplay {
    -Update() void
  }

  class TemperatureStatsDisplay {
    -Update() void
  }

  IObserver ..|> AbstractObserver
  AbstractObserver --|> AbstractStatsObserver
  AbstractObserver --|> Display
  AbstractStatsObserver --|> PressureStatsDisplay
  AbstractStatsObserver --|> HumStatsDisplay
  AbstractStatsObserver --|> TemperatureStatsDisplay

  AbstractObserver o--> ISubject

  class ISubject {
    <<interface>>
    +Subscribe(SubscribeType type, std::weak_ptr~IObserver~ observer) void
    +Unsubscribe(SubscribeType type, std::weak_ptr~IObserver~ observer) void
    +UnsubscribeObserver(std::weak_ptr~IObserver~ observer) void
    +UnsubscribeAllByType(SubscribeType type) void
    +NotifyObservers() void
    +GetData() T

    +NotifyAll() void
    +Notify(SubscribeType type) void
  }

  class Subject {
    -m_observers std::set~std::weak_ptr~IObserver~~
  }

  class WeatherData {
    +GetTemperature() double
    +GetHumidity() double
    +GetPressure() double
    +MeasurementsChanged() void
    +GetData() WeatherInfo

    +SetMeasurements(double temp, double humidity, double pressure) void

    m_temperature double 
    m_humidity double 
    m_pressure double 
  }

  ISubject ..|> Subject
  Subject ..|> SubscribeType : use
  Subject --|> WeatherData

  Subject o--> IObserver
  WeatherData --> WeatherInfo : creates

  class WeatherInfo {
    +temperature double 
    +humidity double 
    +pressure double 
  }
